### ISSUE TITLE
Roadmap: Support of mod_security?

### ISSUE THREAD

**Issue by N0rthg4t3** [VultureProject/vulture-base#66]
Please do not be too harsh on me, this is my first issue I am filing on this platform at all.

So far I really enjoyed working with Vulture 4 - especially in comparison to some "streamlined" products like Kemp or Zevenet LB. I also think that mod_defender provides an interesting module choice. Great work, keep it up! And if there is a part in contribution that involves testing of several features, I would be up to that task.

Recently I noticed that in the documentation of Vulture 3.X you mention an integration of mod_security and the OWASP Top 10 CRS. My post therefore is not an "issue" in a literal way, more of a question: Are there any plans on your roadmap to integrate mod_security in Vulture 4 or will this not be supported in long terms?

**Comment by N0rthg4t3** [comment]
My question has been partly answered through the updated project's website, I encourage everyone to take a look for more information.

**Comment by jjourdin** [comment]
Hello,

Thank you for your request and thank you for proposing your help !
I take the opportunity to clarify some points about the project ;-)

Few know, but mod_security3 has already been packaged into vulture4/haproxy in the form of a SPOA filter, just like mod_defender. But it has never been configurable from the GUI and was eventually removed. And so will mod_defender be.
Why ? Two different components but quite the same reasons...

 - mod_security : This is an old school technology, based on "rules" that supposes you to know the attack before it occurs. We do not believe in this arrogant concept anymore, not in 2022, in the age of machine learning and artificial intelligence. Blacklist approach gives a false feeling of protection and is prone to false-positives. When you are aware of a vulnerability, there is always a possibility to write an haproxy ACL by hand. The next version of Vulture-GUI will embed HAPROXY ACL that will do almost the same job, except "full" body inspection. At least you will have strong HTTP protocol compliance and basic security protection "out of the box".
 
If you wanna play, I can provide the source code of the ModSecurity3 SPOA Module, it is easy to compile and easy to set up a filtering service to work with haproxy and OWASP CRS rules. But due to the nature of spoa and haproxy, body inspection is not complete / efficient.

 - mod_defender: The Haproxy SPOA filter has been developped on top of Vulture3's httpd mod_defender, itself based on naxsi for nginx. The haproxy code is kind of a wrapper of APR structures designed for Apache, this is nonsense and not efficient, it should be fully rewritten. ModDefender still uses rules, with whitelist approach this time, better than mod_security, but this is still old-fashion rules and still prone to false-positives. Also, the process is not efficient when you have to deal with hundred of websites, or more : You have to collect and store logs for a given period of time, then you need to process logs, to build a ruleset... and to maintain it over time.

For both modules, integration into a graphical GUI is a pain and difficult to maintain, that's why they will be removed very soon. We MAY bring mod_defender back after a full code rewrite, but I doubt we will and certainly not within the GUI. It involves too much resources (storing log into mongoDB for instance) for big deployments.

So, is there any hope for Vulture 4 to have a _good_ web firewall ? 
Short answer is YES.

Question is when. This one is more difficult to answer, because WAF is not our main focus right know. The good news is that we still have a (small) team working on it and currently testing new approaches based on machine learning. If you are aware of efficient technics or like to work on the subject with us, drop me an email at jeremie.jourdin at advens.fr so that we can discuss more about it.

Current approaches are focused on http request fingerprinting and neural network based filtering.

Jérémie
